name: filesize_i18n
description: A package to get humanized and internationalized file sizes. Translate raw file size into human readable strings.
homepage: https://github.com/sarbogast/filesize_i18n

version: 2.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_cov: ^1.0.1
  pedantic: ^1.11.1

flutter:
  generate: true